# Generated by Django 2.2.3 on 2019-08-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='person_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatives',
            name='person_id',
            field=models.ForeignKey(default=0, on_delete='CASCADE', to='shop.Person'),
            preserve_default=False,
        ),
    ]
